CXX := gcc
CXXFLAGS := -O3 -march=native -mfma -fopenmp -DNDEBUG -g
LDFLAGS := -fopenmp -lnuma

BASELINE_DIR := src/baseline
OPTIMIZED_DIR := src/optimized
BUILD_DIR := bin
OPTIMIZED_TARGET := $(BUILD_DIR)/sw_opt
OPTIMIZED_SRC := $(OPTIMIZED_DIR)/sw_opt.c

BASELINE_TARGET := $(BUILD_DIR)/sw_baseline
BASELINE_SRC := $(BASELINE_DIR)/sw_baseline.c

all: $(OPTIMIZED_TARGET) $(BASELINE_TARGET)

$(OPTIMIZED_TARGET): $(OPTIMIZED_SRC)
	mkdir -p $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $(OPTIMIZED_SRC) -o $(OPTIMIZED_TARGET) $(LDFLAGS)

$(BASELINE_TARGET): $(BASELINE_SRC)
	mkdir -p $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $(BASELINE_SRC) -o $(BASELINE_TARGET) $(LDFLAGS)

clean:
	rm -f $(OPTIMIZED_TARGET) $(BASELINE_TARGET)